name: Deploy to the server

on: [push]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Copying all the code
        uses: actions/checkout@v4
      
      - name: Deploy to server
        run: |
          echo "Deploying to server..."

      - name: auth using gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Accessing the VM  
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} --zone=${{ secrets.GCP_ZONE }} \
          --command="sudo touch testing_vm.txt" \
          -- -o StrictHostKeyChecking=no
